name: Install GTest
description: Install and setup GTest for linking and building test application
inputs:
  version:
    description: The desired GTest version to install
    required: false
    default: "1.17.0"
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/install-gtest.sh ${{ inputs.version }}
      shell: bash
