name: Install GTest
description: Install and setup GTest for linking and building test application
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/install-gtest.sh ${{ inputs.version }}
      shell: bash
