name: Regular badging sequence
description: Publishes a badge based on the job status
inputs:
  category:
    description: The subfolder where to group the badges
    required: true
  label:
    description: The label to you in the badge (this should be unqie for each badge in a category)
    required: true
  github_token:
    description: The token to use to publish the changes
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: badge success
      if: github.event_name == 'push' && success()
      uses: ./.github/actions/badge/success
      with:
        category: ${{ inputs.category }}
        label: ${{ inputs.label }}
        github_token: ${{ inputs.github_token }}

    - name: badge failure
      if: github.event_name == 'push' && !success()
      uses: ./.github/actions/badge/failure
      with:
        category: ${{ inputs.category }}
        label: ${{ inputs.label }}
        github_token: ${{ inputs.github_token }}
