name: Make a Failure Badge
description: Publishes a badge indicating a 'Failing' status
inputs:
  category:
    description: The subfolder where to group the badges
    required: true
  label:
    description: The label to you in the badge (this should be unqie for each badge in a category)
    required: true
  github_token:
    description: The token to use to publish the changes
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/badge
      with:
        category: ${{ inputs.category }}
        label: ${{ inputs.label }}
        message: Failing
        color: red
    - uses: ./.github/actions/badge/publish
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
