language: cpp
compiler: gcc

os: linux
dist: xenial

install:
  - sudo apt update
  - sudo apt install libgtest-dev
  - (cd /usr/src/gtest && sudo `which cmake` .)
  - sudo make -C /usr/src/gtest
  - sudo ln -s /usr/src/gtest/libgtest.a /usr/lib/libgtest.a
  - sudo ln -s /usr/src/gtest/libgtest_main.a /usr/lib/libgtest_main.a

script:
  - cmake . -DJWT_BUILD_TESTS=ON
  - make
  - ./tests/jwt-cpp-test
