name: "Render `defaults.h` Template"
description: "Generate the `defaults.h` header file for a JSON library"
inputs:
  traits_name:
    description: "Name of the traits structure to be used. Typically in the format `author_repository` or equivilant"
    required: true
  library_name:
    description: "Name of the JSON library."
    required: true
  library_url:
    description: "URL to the JSON library."
    required: true
  disable_default_traits:
    description: "Set the macro to disable the default traits"
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install mustache
      shell: bash
    - uses: actions/github-script@v5
      with:
        script: |
          const mustache = require('mustache')
          const path = require('path')
          const fs = require('fs')

          const traitsName = core.getInput('traits_name', { required: true })
          console.log(`Rendering ${traitsName}!`)

          const libraryName = core.getInput('library_name', { required: true })
          const libraryUrl = core.getInput('library_url', { required: true })
          const disableDefault = core.getInput('disable_default_traits') === 'true'

          const template = fs.readFileSync(path.join('include', 'jwt-cpp', 'traits', 'defaults.h.mustache'), 'utf8')
          const content = mustache.render(template, {
              traits_name: traitsName,
              traits_name_upper: traitsName.toUpperCase(),
              library_name: libraryName,
              library_url: libraryUrl,
              disable_default_traits: disableDefault,
          })
          const outputDir = path.join('include', 'jwt-cpp', 'traits', traitsName.replace('_', '-'))
          fs.mkdirSync(outputDir, { recursive: true })
          fs.writeFileSync(path.join(outputDir, 'defaults.h'), content)
