name: "Render `defaults.h` Template"
description: "Generate the `defaults.h` header file for a JSON library"
inputs:
  traits_name:
    description: "Name of the traits structure to be used. Typically in the format `author_repository` or equivalent"
    required: true
  library_name:
    description: "Name of the JSON library."
    required: true
  library_url:
    description: "URL to the JSON library."
    required: true
  disable_default_traits:
    description: "Set the macro to disable the default traits"
    required: false
    default: "true"
outputs:
  file_path:
    description: "Absolute path which the 'defaults.h' was written to"
    value: ${{ steps.script.outputs.result }}
runs:
  using: composite
  steps:
    - shell: bash
      id: script
      run: |
        cmake -P cmake/render-defaults.cmake -DTRAITS_NAME=${{ inputs.traits_name }} \
        -DLIBRARY_NAME=${{ inputs.library_name }} -DLIBRARY_URL="${{ inputs.library_url }}" \
        -DJWT_DISABLE_PICOJSON=${{ inputs.disable_default_traits }}
        echo "result=$(echo $OUTPUT_FILE)" >> $GITHUB_OUTPUT
