name: Make a Success Badge
description: Publishes a badge indicating a successful 'Passing' status
inputs:
  category:
    description: The subfolder where to group the badges
    required: true
  label:
    description: The label to you in the badge (this should be unqie for each badge in a category)
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/badge
      with:
        category: ${{ inputs.category }}
        label: ${{ inputs.label }}
    - uses: ./.github/actions/badge/publish
