name: Support Question
description: Have some questions? We can offer help.
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Don't hesitate to ask any question you might have!
  - type: textarea
    id: question
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
