name: Install jsoncons
description: Install jsoncons for building test application
inputs:
  version:
    description: The desired jsoncons version to install
    required: false
    default: "1.3.2"
runs:
  using: composite
  steps:
    - run: |
        cd /tmp
        wget https://github.com/danielaparker/jsoncons/archive/v${{ inputs.version }}.tar.gz
        tar -zxf /tmp/v${{ inputs.version }}.tar.gz
        cd jsoncons-${{ inputs.version }}
        cmake .
        sudo cmake --install .
      shell: bash
