name: Install jsoncons
description: Install jsoncons for building test application
inputs:
  version:
    description: The desired jsoncons version to install
    required: false
    default: "1.3.2"
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/install-jsoncons.sh ${{ inputs.version }}
      shell: bash
