name: Install Boost.JSON
description: Install Boost.JSON for building test application
inputs:
  version:
    description: The desired Boost.JSON version to install
    required: false
    default: "1.90.0"
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/install-boost-json.sh ${{ inputs.version }}
      shell: bash
