name: Install lcov
description: Install lcov from official tarball and required Perl modules

inputs:
  version:
    description: The lcov version to install
    required: false
    default: "2.3.1"

runs:
  using: composite
  steps:
    - name: Install system dependencies
      run: |
        sudo apt-get install -y \
            libcapture-tiny-perl \
            libdatetime-perl \
            libfile-slurp-perl \
            libfile-copy-recursive-perl \
            libsort-naturally-perl
      shell: bash

    - name: Download lcov tarball
      run: |
        cd /tmp
        wget https://github.com/linux-test-project/lcov/releases/download/v${{ inputs.version }}/lcov-${{ inputs.version }}.tar.gz
        tar -zxf lcov-${{ inputs.version }}.tar.gz
      shell: bash

    - name: Build and install lcov
      run: |
        cd /tmp/lcov-${{ inputs.version }}
        sudo make install
      shell: bash
