name: Comment Linting Results
description: Add a comment to a pull request with any `git diff` present
inputs:
  linter_name:
    description: The name of the tool to credit in the comment
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v5
      env:
        LINTER_NAME: ${{ inputs.linter_name }}
      with:
        script: |
          if (context.eventName !== 'pull_request') return

          let output = ''
          const options = {
            listeners: {
              stdout: data => output += data.toString()
            },
          }
          await exec.exec('git', ['--no-pager', 'diff', '--minimal', 'HEAD'], options)
          if(output === '') return
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 ${process.env.LINTER_NAME}: linting had some concerns
            
            <details><summary>Suggestion</summary>

            \`\`\`diff
            ${output}
            \`\`\`

            </details>

            `
          })
    - run: exit $(git status -uno -s | wc -l)
      shell: bash
