name: Install CMake
description: Install and setup CMake for building
runs:
  using: composite
  steps:
      - name: install cmake
        run: |
          wget https://cmake.org/files/v3.12/cmake-3.12.4.tar.gz
          tar -zxf cmake-3.12.4.tar.gz
          cd cmake-3.12.4
          ./bootstrap
          make -j $(nproc)
          sudo make install