name: Install CMake
description: Download, Build and Cache CMake
inputs:
  version:
    description: The desired CMake version to install
    required: true
  url:
    description: "The corresponding URL to download the source code from"
    required: true
runs:
  using: composite
  steps:
  - name: Cache CMake
    id: cache-cmake
    uses: actions/cache@v3
    with:
      path: cmake-${{ inputs.version }}
      key: ${{ runner.name }}-${{ runner.os }}-${{ runner.arch }}-cmake-${{ inputs.version }}
  - name: Build cmake
    if: steps.cache-cmake.outputs.cache-hit != 'true'
    run: |
      wget ${{ inputs.url }}
      tar -zxf cmake-${{ inputs.version }}.tar.gz
      cd cmake-${{ inputs.version }}
      ./bootstrap
      make -j $(nproc)
    shell: bash
  - name: Install cmake
    run: |
      cd cmake-${{ inputs.version }}
      sudo make install
    shell: bash
