name: Install CMake
description: Download, Build and Cache CMake
inputs:
  version:
    description: The desired CMake version to install
    required: true
  url:
    description: "The corresponding URL to download the source code from"
    required: true
  cache-key:
    description: "The key to use for caching the built CMake. Defaults to a key based on the version and runner architecture."
    required: false
    default: ${{ runner.os }}-${{ runner.arch }}
runs:
  using: composite
  steps:
    # https://github.com/actions/runner-images/blob/b35930c1765585449578960a3e4b17de818ca923/images/ubuntu/scripts/build/configure-environment.sh#L13
  - run: echo "image_os=$ImageOS" >> "$GITHUB_OUTPUT"
    id: image_os
    shell: bash
  - name: Cache CMake
    id: cache-cmake
    uses: actions/cache@v4
    with:
      path: cmake-${{ inputs.version }}
      key: ${{ inputs.cache-key }}-${{ steps.image_os.outputs.image_os }}-cmake-${{ inputs.version }}
  - name: Build cmake
    if: steps.cache-cmake.outputs.cache-hit != 'true'
    run: |
      wget ${{ inputs.url }}
      tar -zxf cmake-${{ inputs.version }}.tar.gz
      cd cmake-${{ inputs.version }}
      ./bootstrap
      make -j $(nproc)
    shell: bash
  - name: Install cmake
    run: |
      cd cmake-${{ inputs.version }}
      # Depending if we run in on a GitHub Actions or from within a Docker image we have different permissions
      if [[ $EUID > 0 ]]; then
        # If we are not root then we need to sudo
        sudo make install
      else
        # Default docker image does not have users setup so we are only root and can not sudo
        make install
      fi
    shell: bash
