name: Cross-Platform CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      # Setup Dependencies
      - if: matrix.os == 'windows-latest'
        run: choco install openssl
      - if: matrix.os == 'macos-latest'
        run: sudo cp /usr/local/opt/openssl@1.1/lib/pkgconfig/*.pc /usr/local/lib/pkgconfig/

      - uses: actions/checkout@v3

      - name: configure
        run: cmake --preset examples

      - name: build
        run: cmake --build --preset examples

      - name: test
        run: |
          cmake --build --preset examples --target rsa-create-run
          cmake --build --preset examples --target rsa-verify-run

      - if: github.event_name == 'push' && always()
        uses: ./.github/actions/badge
        with:
          category: cross-platform
          label: ${{ matrix.os }}
