name: Cross-Platform CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - if: matrix.os == 'windows-latest'
        run: choco install openssl

      - if: matrix.os == 'macos-latest'
        run: cp /usr/local/opt/openssl@1.1/lib/pkgconfig/*.pc /usr/local/lib/pkgconfig/

      - uses: actions/checkout@v2
      - run: cmake -E make_directory ${{github.workspace}}/build

      - name: configure
        shell: bash # access regardless of the host operating system
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DJWT_BUILD_EXAMPLES=ON

      - name: build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build .

      - if: matrix.os != 'windows-latest'
        name: test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          ./example/rsa-create
          ./example/rsa-verify

      - if: matrix.os == 'windows-latest'
        name: test
        working-directory: ${{github.workspace}}/build
        run: |
          example\Debug\rsa-create.exe
          example\Debug\rsa-verify.exe

      - name: badge success
        if: github.event_name == 'push' && success()
        uses: ./.github/actions/badge
        with:
          category: cross-platform
          label: ${{ matrix.os }}

      - name: badge failure
        if: github.event_name == 'push' && !success()
        uses: ./.github/actions/badge
        with:
          category: cross-platform
          label: ${{ matrix.os }}
          message: Failing
          color: red

      - name: badge publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: badges
          publish_dir: ./badges
          keep_files: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
