name: Cross-Platform CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - run: cmake -E make_directory ${{ github.workspace }}/build

      - name: configure
        shell: bash # access regardless of the host operating system
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -DJWT_BUILD_EXAMPLES=ON

      - name: build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: cmake --build .

      - name: test
        run: |
          cmake --build build/ --target rsa-create-run
          cmake --build build/ --target rsa-verify-run

      - if: github.event_name == 'push' && always()
        uses: ./.github/actions/badge
        with:
          category: cross-platform
          label: ${{ matrix.os }}
