name: Header-Only CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "include/jwt-cpp/**"
      - ".github/workflows/header-only.yml"

jobs:
  include-folder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install libssl-dev
    - run: mkdir -p example/header-only/
    - run: cp -r include example/header-only/
    - run: cp example/traits/nlohmann-json.cpp example/header-only/
    - name: compile
      working-directory: example/header-only/
      run: g++ -Iinclude -c nlohmann-json.cpp
    - name: link
      working-directory: example/header-only/
      run: g++ -o nlohmann-json -Iinclude nlohmann-json.o

  only-jwt-h:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
