# This is a basic workflow to help you get started with Actions

name: Nuget

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'v0.6.0'
      
      # Deploy NuGet so we can call the pack and push cmds
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.7
        with:
          nuget-api-key: ${{ secrets.nuget_api_key }}
          
      # Package the nusepc file
      - name: Create NuGet pkg
        working-directory: ./nuget
        run: nuget pack jwt-cpp.nuspec
        
      # Publish nuget pkg
      - name: Publish NuGet pkg
        working-directory: ./nuget
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json'
          