name: Package Manager CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "example/conan/**"
      - "example/hunter/**"
      - "example/vcpkg/**"
      - ".github/actions/**"
      - ".github/workflows/package-managers.yml"

jobs:
  conan:
    defaults:
      run:
        working-directory: example/conan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - uses: actions/setup-python@v4
    - run: python3 -m pip install conan --upgrade
    - run: conan config init --force

    - run: conan install .
    - run: cmake .
    - run: cmake --build .

    - run: echo "run conan example"

  hunter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  vcpkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
