name: Package Manager CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "example/conan/**"
      - "example/hunter/**"
      - "example/vcpkg/**"
      - ".github/actions/**"
      - ".github/workflows/package-managers.yml"

jobs:
  conan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  hunter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  vcpkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
