name: Specific Targets CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "CMakeLists.txt"
      - "cmake/**"
      - "include/jwt-cpp/**"
      - "tests/cmake/**"
      - ".github/actions/**"
      - ".github/workflows/targets.yml"

jobs:
  centos7:
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
    steps:
      - run: sudo yum group install "Development Tools"
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: setup
        run: |
          mkdir build
          cd build
          cmake ..
          sudo cmake --install .
      - name: test
        working-directory: tests/cmake
        run: |
          cmake . -DTEST:STRING="defaults-enabled"
          cmake --build .
