name: Specific Targets CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "CMakeLists.txt"
      - "cmake/**"
      - "include/jwt-cpp/**"
      - "tests/cmake/**"
      - ".github/actions/**"
      - ".github/workflows/targets.yml"

jobs:
  gcc-4-8:
    name: GCC 4.8
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt-get install gcc-4.8
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install/cmake

      - name: setup
        run: |
          mkdir build
          cd build
          cmake ..
          sudo cmake --install .
      - name: test
        working-directory: tests/cmake
        run: |
          cmake . -DTEST:STRING="defaults-enabled"
          cmake --build .
